USE master;
GO

IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QUANLYDEAN')
    DROP DATABASE QUANLYDEAN;
GO

CREATE DATABASE QUANLYDEAN;
GO

USE QUANLYDEAN;
GO

CREATE TABLE NHANVIEN (
    MANV CHAR(9) PRIMARY KEY,
    HONV NVARCHAR(10) NOT NULL,
    TENLOT NVARCHAR(10) NOT NULL,
    TENNV NVARCHAR(10) NOT NULL,
    NGSINH DATETIME,
    DCHI NVARCHAR(30),
    PHAI NVARCHAR(3) CHECK (PHAI IN (N'Nam', N'Nữ')),
    MA_NQL CHAR(9),
    LUONG INT DEFAULT 10000,
    PHG INT
);
GO

CREATE TABLE PHONGBAN (
    MAPHG INT PRIMARY KEY,
    TENPHG NVARCHAR(20) UNIQUE NOT NULL,
    TRPHG CHAR(9) FOREIGN KEY REFERENCES NHANVIEN(MANV),
    NGAY_NC DATETIME DEFAULT GETDATE()
);
GO

ALTER TABLE NHANVIEN ADD CONSTRAINT NV_PHG_FK FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG);
GO

CREATE TABLE DEAN (
    MADA INT PRIMARY KEY,
    TENDA NVARCHAR(20) NOT NULL,
    DDIEM_DA NVARCHAR(20),
    PHONG INT FOREIGN KEY REFERENCES PHONGBAN(MAPHG)
);
GO

CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(9) NOT NULL REFERENCES NHANVIEN(MANV),
    TENTN NVARCHAR(30) NOT NULL,
    PHAI NCHAR(3) CHECK (PHAI IN (N'Nam', N'Nữ')),
    NGSINH DATETIME,
    QUANHE NVARCHAR(20),
    CONSTRAINT TN_MATEN_PK PRIMARY KEY (MA_NVIEN, TENTN)
);
GO

CREATE TABLE PHANCONG (
    MA_NVIEN CHAR(9),
    SODA INT,
    THOIGIAN DECIMAL(5,2),
    CONSTRAINT PC_MASO_PK PRIMARY KEY (MA_NVIEN, SODA)
);
GO

CREATE TABLE DIADIEM_PHG (
    MAPHG INT,
    DIADIEM NVARCHAR(20),
    CONSTRAINT DD_PHG_PK PRIMARY KEY (MAPHG, DIADIEM)
);
GO

BEGIN /** NHANVIEN **/
	ALTER TABLE NHANVIEN
	NOCHECK CONSTRAINT ALL
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Đinh', N'Bá', N'Tiến', '009', '02/11/1960', N'119, Cống Quỳnh, TP.HCM', N'Nam', 30000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Nguyễn', N'Thanh', N'Tùng', '005', '08/20/1962', N'222, Nguyễn Văn Cừ, TP.HCM', N'Nam', 40000, '006', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Bùi', N'Ngọc', N'Hằng', '007', '03/11/1954', N'332, Nguyễn Thái Học, TP.HCM', N'Nam', 25000, '001', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Lê', N'Quỳnh', N'Như', '001', '02/01/1967', N'291, Hồ Văn Huê, TP.HCM', N'Nữ', 43000, '006', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Nguyễn', N'Mạnh', N'Hùng', '004', '03/04/1967', N'95, Bà Rịa - Vũng Tàu', N'Nam', 38000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Trần', N'Thanh', N'Tâm', '003', '05/04/1957', N'34, Mai Thị Lự, TP.HCM', N'Nam', 25000, '005', 5)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES (N'Trần', N'Hồng', N'Quang', '008', '09/01/1967', N'45, Lê Hồng Phong, TP.HCM', N'Nam', 25000, '001', 4)
	INSERT INTO NHANVIEN (HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, PHG)
	VALUES (N'Phạm', N'Văn', N'Vinh', '006', '01/01/1965', N'45, Trưng Vương', N'Nữ', 55000, 1)
	ALTER TABLE NHANVIEN
	CHECK CONSTRAINT ALL
	UPDATE NHANVIEN SET MA_NQL = '006' WHERE MANV = '005'
	UPDATE NHANVIEN SET LUONG = 30000,PHAI='Nam',DCHI=N'119, Cống Quỳnh, TP.HCM' WHERE MANV ='009'
END
SELECT * FROM NHANVIEN;
GO
